version: "3.9"

services:
  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu
    tty: true
    command: sleep infinity

  ubuntu2:
    image: ubuntu:latest
    container_name: ubuntu2
    tty: true
    command: sleep infinity
