name: 'mg-bicep'

trigger:
  branches:
    include:
      - main

pool: self-hosted

steps:

  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'azure-service-connection'
      azurePowerShellVersion: 'LatestVersion'
      ScriptType: 'InlineScript'
      Inline: |
        New-AzManagementGroupDeploymentStack `
          -Name 'mg-bicep' `
          -ManagementGroupId 'c0f414ff-9e2d-4011-929c-fe21ed71b218' `
          -Location 'Sweden Central' `
          -ActionOnUnmanage DeleteAll `
          -DenySettingsMode None `
          -TemplateParameterFile './mg/mgado.bicepparam' `
          -Force
      errorActionPreference: 'stop' # 'stop' | 'continue' | 'silentlyContinue'.
      FailOnStandardError: false
      pwsh: true
    displayName: 'mg bicep deploy'
