name: 'sub-bicep-ado'

trigger:
  branches:
    include:
      - main

pool: self-hosted

steps:
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'papliba-mi-mg-01'
      azurePowerShellVersion: 'LatestVersion'
      ScriptType: 'InlineScript'
      Inline: |
        New-AzManagementGroupDeploymentStack `
          -Name 'platform-sub' `
          -ManagementGroupId 'platform' `
          -Location 'Sweden Central' `
          -ActionOnUnmanage 'DetachAll' `
          -DenySettingsMode 'None' `
          -TemplateParameterFile './lz/standard/main.bicepparam' `
          -Force
      errorActionPreference: 'stop'
      FailOnStandardError: false
      pwsh: true
    displayName: 'sub bicep deploy'
