name: 'Sub Bicep ado'

trigger:
  branches:
    include:
      - main

pool: self-hosted

steps:

  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'azure-service-connection'
      azurePowerShellVersion: 'LatestVersion'
      ScriptType: 'InlineScript'
      Inline: |
        New-AzManagementGroupDeployment `
          -Name 'sub-bicep-whatif' `
          -ManagementGroupId 'platform-prod' `
          -Location 'Sweden Central' `
          -TemplateParameterFile './subscription/subado.bicepparam' `
          -WhatIf
      errorActionPreference: 'stop'
      FailOnStandardError: false
      pwsh: true
    displayName: 'suv bicep whatif'


  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'azure-service-connection'
      azurePowerShellVersion: 'LatestVersion'
      ScriptType: 'InlineScript'
      Inline: |
        New-AzManagementGroupDeployment `
          -Name 'sub-bicep-deploy' `
          -ManagementGroupId 'platform-prod' `
          -Location 'Sweden Central' `
          -TemplateParameterFile './subscription/subado.bicepparam' `
          -Force
      errorActionPreference: 'stop'
      FailOnStandardError: false
      pwsh: true
    displayName: 'sub bicep deploy'
