name: MG Bicep

on: 
  push: 
    branches: 
      - main

permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.ROOT_SUB_ID }}
          enable-AzPSSession: true


      - name: mg bicep whatif 
        uses: azure/powershell@v2
        with:
          inlineScript: |
            # Create whatif deployment stack at subscription scope
            New-AzSubscriptionDeploymentStack `
            -Name 'mg-bicep' `
            -Location 'Sweden Central' `
            -ActionOnUnmanage DeleteAll `
            -DenySettingsMode DenyWriteAndDelete `
            -TemplateParameterFile './mg/mg.bicepparam' `
            -Force `
            -WhatIf
          azPSVersion: "latest"

      - name: mg bicep deploy
        uses: azure/powershell@v2
        with:
          inlineScript: |
            # Create deployment stack at subscription scope
            New-AzSubscriptionDeploymentStack `
            -Name 'mg-bicep' `
            -Location 'Sweden Central' `
            -ActionOnUnmanage DeleteAll `
            -DenySettingsMode DenyWriteAndDelete `
            -TemplateParameterFile './mg/mg.bicepparam' `
            -Force
          azPSVersion: "latest"
